//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chhayatech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clist
    {
        public string cid { get; set; }
        public string cname { get; set; }
        public string cduration { get; set; }
        public string cfee { get; set; }
    }
}
