//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chhayatech.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class reg
    {

        [DisplayName("Mobile No")]
        public string mobileno { get; set; }

        [DisplayName("Email Id")]
        public string emailid { get; set; }

        [DisplayName("Name")]
        public string name { get; set; }
    }
}
