//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chhayatech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ulogin
    {
        public string Uid { get; set; }
        public string Uname { get; set; }
        public string Upass { get; set; }
        public string Urole { get; set; }
    }
}
